### ISSUE TITLE
Scripts doesn't work with MacOs Catalina

### ISSUE THREAD

**Issue by vgeannin** [orangeturtle739/photos-export#15]
Hi,

I'm trying to use your script with Photos on MacOS 10.15 Catalina.
And it doesn't work.
It seems that the Photos Database  have not the same structure than before.

Vincent

**Comment by orangeturtle739** [comment]
1. What version of Photos are you running?
2. What is the exact error? (please paste the command you ran and the entire output).

**Comment by vgeannin** [comment]
Hi,,

1 : I'm using MacoOS Catalina (10.15.0) , Photos Version 5.0 (101.15.190)
2 : 
$ ./folder_structure.py ../../Pictures/Photos\ Library.photoslibrary/
Traceback (most recent call last):
  File "./folder_structure.py", line 96, in <module>
    run(sys.argv[1], sys.argv[2])
IndexError: list index out of range

When I look at the database structure of this version of Photos, it change a lot 

Vincent

**Comment by orangeturtle739** [comment]
Please see the [readme](https://github.com/orangeturtle739/photos-export).

`folder_structure.py` takes **2** command line arguments:
```
$ ./folder_structure.py <library_dir> <output_dir>
```

**Comment by vgeannin** [comment]
Sorry, I make a mistake when I relaunch the script : 
iMac:photos-export vincent$ ./folder_structure.py ../../Pictures/Photos\ Library.photoslibrary/ ../../test.photo/
Traceback (most recent call last):
  File "./folder_structure.py", line 96, in <module>
    run(sys.argv[1], sys.argv[2])
  File "./folder_structure.py", line 47, in run
    folders_table.execute('SELECT * FROM ' + FOLDER_TABLE + ' WHERE isInTrash=0')
sqlite3.OperationalError: **no such table: RKFolder**

**Comment by orangeturtle739** [comment]
It looks like they did indeed change something about the database. I'm happy to accept a pull request if you can figure it out and fix it.

**Comment by alexantao** [comment]
Hi,
I don't have the new Photos.app. I have Photos 3.0, from High Sierra, and can't update because my MacBook is too old
. 
If you could make some test database, with just some photos and folders, I'd be glad to try to fix it.

Regards...

**Comment by vgeannin** [comment]
I have made some research and it seems that the database have the same structure than the Photos IOS database.

Regards

**Comment by alexantao** [comment]
The message says that a Table was not found. There are a lot of reasons for that, like the DB is corrupted, the table has another name now, it may not be created (don't think so...). I can't predict what's happening until I take a look inside the database. 
You may try open it with a DBBrowser and list all the tables to see which has the name like the RKFolder.

**Comment by vgeannin** [comment]
see below the list of all tables : 
name                                    
ACHANGE                                 
ATRANSACTION                            
ATRANSACTIONSTRING                      
ZADDITIONALASSETATTRIBUTES              
ZADJUSTMENT                             
ZALBUMLIST                              
ZASSETANALYSISSTATE                     
ZASSETDESCRIPTION                       
ZCLOUDFEEDENTRY                         
ZCLOUDMASTER                            
ZCLOUDMASTERMEDIAMETADATA               
ZCLOUDRESOURCE                          
ZCLOUDSHAREDALBUMINVITATIONRECORD       
ZCLOUDSHAREDCOMMENT                     
ZCODEC                                  
ZCOMPUTEDASSETATTRIBUTES                
ZDEFERREDREBUILDFACE                    
ZDETECTEDFACE                           
ZDETECTEDFACEGROUP                      
ZDETECTEDFACEPRINT                      
ZEDITEDIPTCATTRIBUTES                   
ZEXTENDEDATTRIBUTES                     
ZFACECROP                               
ZFILESYSTEMBOOKMARK                     
ZFILESYSTEMVOLUME                       
ZGENERICALBUM                           
ZGENERICASSET                           
ZINTERNALRESOURCE                       
ZKEYWORD                                
ZLEGACYFACE                             
ZMEDIAANALYSISASSETATTRIBUTES           
ZMEMORY                                 
ZMOMENT                                 
ZMOMENTLIST                             
ZMOMENTSHARE                            
ZMOMENTSHAREPARTICIPANT                 
ZPERSON                                 
ZPERSONREFERENCE                        
ZPHOTOSHIGHLIGHT                        
ZSCENECLASSIFICATION                    
ZSCENEPRINT                             
ZSEARCHDATA                             
ZSUGGESTION                             
ZUNIFORMTYPEIDENTIFIER                  
ZUNMANAGEDADJUSTMENT                    
Z_17CLUSTERREJECTEDPERSONS              
Z_17REJECTEDPERSONS                     
Z_17REJECTEDPERSONSNEEDINGFACECROPS     
Z_1KEYWORDS                             
Z_25ALBUMLISTS                          
Z_26ASSETS                              
Z_34MEMORIESBEINGCURATEDASSETS          
Z_34MEMORIESBEINGEXTENDEDCURATEDASSETS  
Z_34MEMORIESBEINGMOVIECURATEDASSETS     
Z_34MEMORIESBEINGREPRESENTATIVEASSETS   
Z_34SUGGESTIONSBEINGKEYASSETS           
Z_34SUGGESTIONSBEINGREPRESENTATIVEASSETS
Z_45INVALIDMERGECANDIDATES              
Z_45MERGECANDIDATES                     
Z_METADATA                              
Z_MODELCACHE                            
Z_PRIMARYKEY                            
Z_RT_GenericAsset_boundedByRect         
Z_RT_GenericAsset_boundedByRect_node    
Z_RT_GenericAsset_boundedByRect_parent  
Z_RT_GenericAsset_boundedByRect_rowid

**Comment by alexantao** [comment]
Too few tables. If this is the entire Database, a lot of changes were made then. My photos.db has 289 tables. We will have to analyse this new DB to see what's changed and take different aproaches according to the version of Photos.db

**Comment by RhetTbull** [comment]
See https://github.com/RhetTbull/osxphotos which I've recently updated to work with Catalina / Photos 5.0 database format.  This library was inspired by photo-export (https://github.com/patrikhson/photo-export) but now significantly re-written.  In particular, look at _process_database5 in https://github.com/RhetTbull/osxphotos/blob/master/osxphotos/__init__.py

**Comment by orangeturtle739** [comment]
Cool, I'll mention that on the readme!

**Comment by danireef** [comment]
Hi, I write here because it seems you are the only persons who know the apple photos database.
I'm currently passed on new macbook pro... and so many problems are come out.
I have almost 700 gb of pictures, in one external SSD, where is also the database structure. When it is connected to my imac (with catalina) everything works, when I connected to may new macbook pro I see the miniatures, but the mac says there is no file... and he wants to search... If I continue, everything on that folder seems ok, but if I switch off and on apple photos, the problem arise again. If I add some pictures from the same SSD from macbook everything is fine on macbook but iMac doesn't see the pictures. I've tried, as in the past, to search inside database, but everything seems fine to me. Any clues? Thanks

**Comment by RhetTbull** [comment]
In Photos | Preferences do you have “Copy items to the Photos library” checked or unchecked?

**Comment by danireef** [comment]
> In Photos | Preferences do you have “Copy items to the Photos library” checked or unchecked?

Thanks for your answer, uUnchecked, I need to have control on my pictures also for editing with Lightroom

**Comment by RhetTbull** [comment]
It may be possible the external SSD is mounted to a different location on each computer.  When you don't have the "Copy items to the Photos library" checked, Photos stores the path to the actual file on disk in the database.   Try mounting the SSD on each computer and in Terminal, type "mount". You should see something like:
```/dev/disk1s6 on /Volumes/SSD Name```

Is the mount point the same on each computer?  It seems unlikely to me this would be the case but could be one possible cause of the issue you're seeing.

By the way, feel free to email me directly at rturnbull at gmail dot com and I'll be glad to try to help you diagnose.  That way we don't clutter this issue thread.

**Comment by danireef** [comment]
Thanks, I've just written, sometimes my email could be on spam :( let me know.
