### ISSUE TITLE
Syntax Error on MacOSX

### ISSUE THREAD

**Issue by alexantao** [orangeturtle739/photos-export#2]
Hi,
  I installed everything the README asked to.
 I'm running HighSierra with python 2.7.15, and when I run the export_photos.py, get the following error:

`python ./extract_photos.py ~/Pictures/Fotos\ do\ Alex.photoslibrary /Volumes/FOTOS\ DIGIKAM
  File "./extract_photos.py", line 195
    file=log_file)
        ^
SyntaxError: invalid syntax`

I'm rusty on my python, but did not see any error on file.
May be the spaces on the pathnames ?

Thanks

**Comment by alexantao** [comment]
Oh, Forgot to ask. Will it work with Photos 3 ? High Siera cannot upgrade anymore.

**Comment by alexantao** [comment]
Well... seems that the script was written on python 3 syntax.
So, to answer my own issue, the followin code must be put in the begining of the script:

`from __future__ import print_function`

This makes the script work.

**Comment by orangeturtle739** [comment]
This is all python 3, yes. The shebang at the top of the file says "#! /usr/bin/env python3".  You could also install python 3 if you wanted to.

As for Photos 3, I'm not sure. If it doesn't work with Photos 3, you can try an older version: https://github.com/orangeturtle739/photos-export/tree/0b456c5ee7fde4c7a35bc742d0677427f65da36e, which might.
