### ISSUE TITLE
Location Error at the end

### ISSUE THREAD

**Issue by alexantao** [orangeturtle739/photos-export#3]
Hi,

   Left running the script on my 865Gb Library, sending the images to a external HD.
  I ran for about 20 hours, the last time I saw, it was on 96%, but when I came back to take a look, found this error below. I don't know if finished extracting all photos. Is there a way to make sure ? I'd rather not run it again, takes too long. Is there a way to know wich photo is wrong ? Thank you

`Inconsistent location: (-15.661620, -47.804955) -> (-15.661509, -47.804621)##################################################################################                   |Traceback (most recent call last):############################################################################################################################################# |
  File "./extract_photos.py", line 231, in <module>
    run(sys.argv[1], sys.argv[2])
  File "./extract_photos.py", line 112, in run
    (latitude, longitude, new_latitude, new_longitude))
TypeError: float argument required, not NoneType
MacBook-Alex:photos-export-master AlexAntao$ 
`

**Comment by orangeturtle739** [comment]
I don't know a good way to figure out where it left off, so I think you'd have to run it again.

What appears to have happened is that the print statement below failed:
https://github.com/orangeturtle739/photos-export/blob/4cc3a241f180c9a995a86ea90cc9e049677e7af7/extract_photos.py#L109-L110

That section of the code is trying to find the GPS coordinates for a group of photos (the master + the edited), and then giving each photo in the group the same coordinates. That isn't quite right however; each photo should really just be getting its own coordinates!

I don't have a library I can test this on anymore, but I think this might fix it: https://github.com/orangeturtle739/photos-export/pull/4. Can you please try it and let me know if it works? Feel free to update that pull request if you want to try to fix it!

**Comment by alexantao** [comment]
Thank you. I'll run it again. More 20hrs of processing... hehe...
Will let you know when I finish. 
I'll try to insert a log file of the files processed. Just to know where it stopped.

**Comment by alexantao** [comment]
just a correction:
Line 165 missing a comma.

**Comment by alexantao** [comment]
Worked ! 19hrs of processing, gone 100% with no errors.  Ran from python3 this time (had it installed before, but didn't know that). 

**But I wonder:** 

According to Finder I have about 763Gb on Masters, but on the destination I got only 712Gb exported. 

Running du -skh on Masters I get 725Gb (on the same 763Gb from Finder)
Runnung du -skh on /Volumes/HDFOTOS (exported from photos-export) I get 712Gb.

Can someone explain what's wrong ?

Where are the Gbs missing ? May be older photos deleted and not yet purged ? I don't think I purged that much. 

![photos-export1](https://user-images.githubusercontent.com/298750/64534027-113f0100-d2eb-11e9-88cd-2ee1ce910f1d.png)
![photos-export3](https://user-images.githubusercontent.com/298750/64534028-11d79780-d2eb-11e9-895b-ed9da410d682.png)

**Comment by orangeturtle739** [comment]
Nice! I'll look through your pull request when I get a chance. Good to know that it worked.

As for the missing files, no promises - I reverse engineered the database format, I could have missed something. Did you figure it out? I saw you made some more issues and #6.

**Comment by orangeturtle739** [comment]
> just a correction:
> Line 165 missing a comma.

Just updated #4. It works right? I should merge it?

**Comment by alexantao** [comment]
Yes, it does. Exported a library with more than 100.000 photos and got no errors.



Thanks

---- Ativado Qua, 18 set 2019 07:34:21 -0300 Jacob Glueck <notifications@github.com> escreveu ----


just a correction:
 Line 165 missing a comma.

Just updated https://github.com/orangeturtle739/photos-export/pull/4. It works right? I should merge it?
