### ISSUE TITLE
album_folders.py getting images from Photos Library

### ISSUE THREAD

**Issue by alexantao** [orangeturtle739/photos-export#5]
Hi,

  I tried running album_photos yesterday.
  All photos were exported and set EXIF by running the other scripts. No errors.
  It started running perfectly, created some albums and copied some files.

  then, I received an exception with the error:

`FileNotFoundError: [Errno 2] No such file or directory: '/Users/AlexAntao/Pictures/Fotos do Alex.photoslibrary/Masters/2017/05/23/20170523-030211/05.10.2003 - Níver Pat2 - 01.jpg' -> '/Volumes/HDFOTOS/Fotos da Família/Casa da Pat - Guará/05.10.2003 - Níver Pat2 - 01.jpg'`

I took a look on the script and noticed that, although it receive the source_dir as argument, it takes the real sourcefile from json file:
`imagesource = data['path']`
and uses it to copy.

that makes no sense, since the files to be copied should be the ones exported before with the previous scripts.

**Comment by alexantao** [comment]
Let's play.
I modified the code to: 

- it now takes the file from source_dir, not Photos Library
- if the file is present to more than one album, it copies to all albuns, then, move the file to the last album listed in .JSON
- check if the file it's trying to copy exists (my library has 720 files missing on disk), to prevent an exception raise

I have done a simple script just to check if the file (listed on database) is missing on disk. But it's not here to include. And I still want to find out how to test for the versions of them. 

The code below DOES NOTHING for now. The MOVE/COPY commands are commented. Instead I put a print just to inform what it's doing. I'll test on my external HD as soon as I can, but seems it works.

**Obs.: modified file attached**

[album_folder.zip](https://github.com/orangeturtle739/photos-export/files/3616827/album_folder.zip)

**Comment by alexantao** [comment]
After some tests on my MacOS, I got some errors to deal with. 
But things are not easy as it looks:

- extract_albuns.py MODIFIES the destination file. In JSON, we have the reference PATH that points to the original file in Photos Library, but the UUID points to the file exported. 
- the file exported has a sequence number attached to it.
- theexported file as spaces changed to "_". 

I don't know why this was done, but due to all those changes the last script will not work correctly. Will have to copy-rename the exported file to reflect the original one.

**Comment by orangeturtle739** [comment]
Does #7 resolve this?

**Comment by alexantao** [comment]
Yes. it does... closing.
