### ISSUE TITLE
export_photos not exporting keywords 

### ISSUE THREAD

**Issue by alexantao** [orangeturtle739/photos-export#8]
After exporting the library, I'm trying to organizing all of then into DIGIKAM.
I noticed then some strange things. 
Almost all photos has no legends, and the Tag list dos not contain all tags/keywords I have on Photos. 
I selected a photo I know, it show with no Title or tags, opened it's JSON generated file and the keywords field is empty, althrough in Photos it has 6 Tags and a title.
It's  JSON has the uuid, path, in_library set, has no albuns, , no keywords, no rating (does it has in Photos ?) ans GPS settings set. 

Should the keywords be included in JSON and after running the set EXIF script included in file ?
Or I misunderstood ?

**Comment by orangeturtle739** [comment]
Albums and keywords are supposed to be exported as tags. The database format may have changed and broken something. I don't have any libraries to test on, but if you figure it out, I'd be happy to merge another PR!

**Comment by alexantao** [comment]
I'll try. In fact, I tried some time ago but lacks me information about the Database structure, what each table/column means. 
Some keywords are present, specially albums, but not all. I'll see next week.

**Comment by alexantao** [comment]
Just created a new Branch and found the problem and commited the modified file. 
on interaction
`            for keyword_id in iter(kc.fetchone, None):
`

there's a mistake on the cursor used. The right one should be:
`            for keyword_id in iter(wc.fetchone, None):
`
Also, my compiler reported some imports were not being used, so I commented. 
Tested on a Test Library with just some photos and all worked perfectly. 
Now the JSON's contains all keywords tagged on a Photo.

**Comment by alexantao** [comment]
I'd like to ask something:
There's a field on script called Rating. My Photos has no rating on anything. The best similar would be the favorite field.

In Digikam there's  a rating field. I know my Photos is not the last version, but if photos 4.0 does not have this option either, we could set the ration to MAX (I think it's 5?) is the photo is marked as favorite. this tag could be easily exported to JSON as the rating.

What do you think ?

**Comment by orangeturtle739** [comment]
Good catch on the `kc` vs. `wc`! For rating, I think setting it 5 is fine.

**Comment by orangeturtle739** [comment]
Resolved by #9, #10, and #11.
